# Generated by Django 4.2.5 on 2024-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_myuser_date_joined_myuser_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='otp',
            field=models.CharField(blank=True, null=True),
        ),
    ]
