# Generated by Django 4.2.5 on 2024-08-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_myuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
