# Generated by Django 4.2.5 on 2024-08-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_myuser_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prfile_pic',
            new_name='profile_pic',
        ),
    ]
