# Generated by Django 4.2.5 on 2024-08-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='available_from',
            field=models.TimeField(default=None, null=True),
            preserve_default=False,
        ),
    ]
