# Generated by Django 4.2.5 on 2024-08-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_doctorprofile_available_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='available_To',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='available_from',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='available_to',
            field=models.TimeField(default=None, null=True),
        ),
    ]
