# Generated by Django 4.2.5 on 2024-08-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_remove_doctorprofile_available_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
