# Generated by Django 4.2.5 on 2024-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0006_alter_slots_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='duration',
            field=models.PositiveIntegerField(default='30'),
            preserve_default=False,
        ),
    ]
