# Generated by Django 4.2.5 on 2024-08-18 06:15

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0007_slots_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='end_date',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
