# Generated by Django 4.2.5 on 2024-08-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0008_slots_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='second_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
