# Generated by Django 4.2.5 on 2024-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0009_alter_doctorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/doctor/profile_pic'),
        ),
    ]
