# Generated by Django 4.2.5 on 2024-08-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0010_doctorprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
