# Generated by Django 4.2.5 on 2024-08-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0011_rename_second_name_doctorprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
