# Generated by Django 4.2.5 on 2024-08-21 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0012_doctorprofile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_verified',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/doctor/documents')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Doctors.doctorprofile')),
            ],
        ),
    ]
