# Generated by Django 4.2.5 on 2024-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0013_remove_doctorprofile_is_verified_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
