# Generated by Django 4.2.5 on 2024-08-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0015_slots_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='start_date',
        ),
    ]
