# Generated by Django 4.2.5 on 2024-08-25 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0018_alter_slots_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='Doctors.doctorprofile'),
        ),
    ]
