# Generated by Django 4.2.5 on 2024-08-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0020_alter_slots_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Doctors.doctorprofile'),
        ),
    ]
