# Generated by Django 4.2.5 on 2024-08-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0022_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
